"""Parse existing test coverage reports and produce R08 findings for uncovered functions.

Reads coverage reports generated by Istanbul/c8 (TypeScript), coverage.py (Python),
or JaCoCo (Java). Does NOT run tests -- that is the developer's responsibility.
"""
from __future__ import annotations

import json
import os
import subprocess
import xml.etree.ElementTree as ET
from typing import Any


def analyze_coverage(project_dir: str, stack: str) -> list[dict[str, str | int | list[str]]]:
    """Analyze existing coverage reports and return findings for uncovered functions.

    Args:
        project_dir: Root directory of the project being audited.
        stack: One of "typescript", "python", or "java".

    Returns:
        List of findings in standard dojutsu format. If no coverage report is
        found, returns a single advisory finding.
    """
    parsers: dict[str, _CoverageParser] = {
        "typescript": _parse_istanbul,
        "python": _parse_coverage_py,
        "java": _parse_jacoco,
    }
    parser = parsers.get(stack)
    if parser is None:
        return [_no_report_finding()]

    findings = parser(project_dir)
    if findings is None:
        return [_no_report_finding()]
    return findings


# -- Type alias for parser callables ------------------------------------------
from typing import Callable

_CoverageParser = Callable[[str], list[dict[str, str | int | list[str]]] | None]


# -- Istanbul / c8 (TypeScript) -----------------------------------------------

def _parse_istanbul(project_dir: str) -> list[dict[str, str | int | list[str]]] | None:
    """Parse coverage/coverage-final.json (Istanbul/c8 format).

    Returns None if the report file does not exist.
    """
    report_path = os.path.join(project_dir, "coverage", "coverage-final.json")
    if not os.path.isfile(report_path):
        return None

    with open(report_path, encoding="utf-8") as fh:
        try:
            data: dict[str, Any] = json.load(fh)
        except (json.JSONDecodeError, ValueError):
            return None

    findings: list[dict[str, str | int | list[str]]] = []
    for file_path, file_cov in data.items():
        fn_map: dict[str, Any] = file_cov.get("fnMap", {})
        f_counts: dict[str, int] = file_cov.get("f", {})
        rel_path = os.path.relpath(file_path, project_dir) if os.path.isabs(file_path) else file_path

        for fn_id, count in f_counts.items():
            if count != 0:
                continue
            fn_info = fn_map.get(str(fn_id), {})
            fn_name: str = fn_info.get("name", f"anonymous_{fn_id}")
            fn_line: int = fn_info.get("line", fn_info.get("loc", {}).get("start", {}).get("line", 1))

            findings.append(_make_coverage_finding(
                file=rel_path,
                line=fn_line,
                description=f"Function '{fn_name}' has zero test coverage",
            ))
    return findings


# -- coverage.py (Python) -----------------------------------------------------

def _parse_coverage_py(project_dir: str) -> list[dict[str, str | int | list[str]]] | None:
    """Parse coverage.json or generate it from .coverage if available.

    Returns None if no coverage data exists.
    """
    coverage_json = os.path.join(project_dir, "coverage.json")

    # If coverage.json does not exist, try generating from .coverage
    if not os.path.isfile(coverage_json):
        dot_coverage = os.path.join(project_dir, ".coverage")
        if not os.path.isfile(dot_coverage):
            return None
        try:
            result = subprocess.run(
                ["coverage", "json", "-o", coverage_json],
                capture_output=True, text=True, cwd=project_dir, timeout=60,
            )
            if result.returncode != 0 or not os.path.isfile(coverage_json):
                return None
        except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
            return None

    with open(coverage_json, encoding="utf-8") as fh:
        try:
            data: dict[str, Any] = json.load(fh)
        except (json.JSONDecodeError, ValueError):
            return None

    findings: list[dict[str, str | int | list[str]]] = []
    files_data: dict[str, Any] = data.get("files", {})

    for file_path, file_info in files_data.items():
        rel_path = os.path.relpath(file_path, project_dir) if os.path.isabs(file_path) else file_path
        functions: dict[str, Any] = file_info.get("functions", {})

        for fn_name, fn_data in functions.items():
            summary: dict[str, Any] = fn_data.get("summary", {})
            percent_covered: float = summary.get("percent_covered", 100.0)

            if percent_covered < 0.01:  # tolerance for floating-point
                fn_line: int = fn_data.get("line", 1)
                findings.append(_make_coverage_finding(
                    file=rel_path,
                    line=fn_line,
                    description=f"Function '{fn_name}' has zero test coverage",
                ))
    return findings


# -- JaCoCo (Java) ------------------------------------------------------------

def _parse_jacoco(project_dir: str) -> list[dict[str, str | int | list[str]]] | None:
    """Parse target/site/jacoco/jacoco.xml for uncovered methods.

    Returns None if the report file does not exist.
    """
    report_path = os.path.join(project_dir, "target", "site", "jacoco", "jacoco.xml")
    if not os.path.isfile(report_path):
        return None

    try:
        tree = ET.parse(report_path)
    except ET.ParseError:
        return None

    root = tree.getroot()
    findings: list[dict[str, str | int | list[str]]] = []

    for package in root.iter("package"):
        pkg_name: str = package.get("name", "").replace("/", ".")
        for cls in package.iter("class"):
            cls_name: str = cls.get("name", "").replace("/", ".")
            source_file: str = cls.get("sourcefilename", "")
            # Build relative path from package + source file
            pkg_path = package.get("name", "")
            rel_path = os.path.join("src/main/java", pkg_path, source_file) if source_file else cls_name

            for method in cls.iter("method"):
                method_name: str = method.get("name", "")
                method_line: int = int(method.get("line", "1"))

                for counter in method.iter("counter"):
                    if counter.get("type") == "METHOD":
                        covered = int(counter.get("covered", "0"))
                        if covered == 0:
                            qualified_name = f"{cls_name}.{method_name}" if cls_name else method_name
                            findings.append(_make_coverage_finding(
                                file=rel_path,
                                line=method_line,
                                description=f"Method '{qualified_name}' has zero test coverage",
                            ))
    return findings


# -- Shared helpers ------------------------------------------------------------

def _make_coverage_finding(
    *,
    file: str,
    line: int,
    description: str,
) -> dict[str, str | int | list[str]]:
    """Create a finding dict matching the dojutsu findings.jsonl schema."""
    return {
        "rule": "R08",
        "severity": "MEDIUM",
        "category": "build",
        "file": file,
        "line": line,
        "end_line": line,
        "snippet": description,
        "current_code": description,
        "description": description,
        "explanation": description,
        "search_pattern": "",
        "phase": 9,
        "effort": "medium",
        "scanner": "coverage-analyzer",
        "confidence": "high",
        "confidence_reason": "Deterministic: coverage report analysis",
        "tool_rule_id": "zero-coverage",
        "cwe": [],
    }


def _no_report_finding() -> dict[str, str | int | list[str]]:
    """Return a single finding when no coverage report is found."""
    return {
        "rule": "R08",
        "severity": "MEDIUM",
        "category": "build",
        "file": "",
        "line": 0,
        "end_line": 0,
        "snippet": "No test coverage report found. Run tests with coverage enabled.",
        "current_code": "",
        "description": "No test coverage report found. Run tests with coverage enabled.",
        "explanation": "No test coverage report found. Run tests with coverage enabled.",
        "search_pattern": "",
        "phase": 9,
        "effort": "medium",
        "scanner": "coverage-analyzer",
        "confidence": "high",
        "confidence_reason": "Deterministic: no coverage report detected",
        "tool_rule_id": "no-coverage-report",
        "cwe": [],
    }
