"""Tests for deterministic inventory tagging."""
from __future__ import annotations

import json
import os
import subprocess
import tempfile


SCRIPT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "scripts",
    "create-inventory.py",
)


class TestCreateInventory:
    def test_generated_marker_tags_file_as_generated(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_dir = os.path.join(tmp, "project")
            audit_dir = os.path.join(tmp, "audit")
            os.makedirs(project_dir, exist_ok=True)
            with open(os.path.join(project_dir, "package.json"), "w") as fh:
                json.dump({"name": "fixture"}, fh)
            with open(os.path.join(project_dir, "client.ts"), "w") as fh:
                fh.write("// Generated by h1\nexport const value = 1;\n")

            result = subprocess.run(
                ["python3", SCRIPT_PATH, project_dir, audit_dir],
                capture_output=True,
                text=True,
                check=False,
            )

            assert result.returncode == 0
            with open(os.path.join(audit_dir, "data", "inventory.json")) as fh:
                inventory = json.load(fh)
            assert inventory["files"][0]["tag"] == "GENERATED"
            assert inventory["files"][0]["skip_reason"] == "Generated source file"
